### ISSUE TITLE
Using updates branch

### ISSUE THREAD

**Issue by erwamartin** [Profab/react-native-ble#1]
Hi @rclai!

I'm currently working on a React Native project and I have to get data from a BLE peripheral.
I see you are doing an amazing work to implement connect and services to this library!

Actually, I have to develop a prototype very quickly in the next few days and I wonder if there is a way to use your fork right now? I tried to use it in my project, but as you are still working on it, I'm getting an error ("Cannot read property 'setup' of undefined" in bindings.ios.js).

Thank you!

**Comment by rclai** [comment]
@erwamartin Did you properly install my updates branch or the master branch?

**Comment by erwamartin** [comment]
Yes, I installed your updates branch. I just pulled the latest version and it's working now :)
Thanks!
